import { Alert, Box, Button, CircularProgress, Paper, Stack, TextField, Typography } from '@mui/material'
import { FormEvent, useState } from 'react'
import { ApiError } from '../api/client'
import { RegstairLogo } from '../brand/RegstairLogo'
import { ThemeModeControl } from '../theme/ThemeModeControl'

async function request<T>(path: string, body?: unknown, headers?: Record<string, string>): Promise<T> {
  const response = await fetch(path, { method: body ? 'POST' : 'GET', credentials: 'same-origin', headers: { Accept: 'application/json', ...(body ? { 'Content-Type': 'application/json' } : {}), ...headers }, body: body ? JSON.stringify(body) : undefined })
  if (!response.ok) throw new ApiError(response.status, `http_${response.status}`)
  return response.json()
}

function PublicFrame({ title, subtitle, eyebrow, wide = false, children }: { title: string; subtitle: string; eyebrow: string; wide?: boolean; children: React.ReactNode }) { return <Box sx={{ alignItems: 'center', display: 'flex', justifyContent: 'center', minHeight: '100dvh', p: { xs: 2, sm: 3 } }}><Stack spacing={3} sx={{ maxWidth: wide ? 520 : 440, width: '100%' }}><Stack direction="row" spacing={1.5} sx={{ alignItems: 'center' }}><RegstairLogo /><Box sx={{ flex: 1 }}><Typography sx={{ fontSize: 22, fontWeight: 760 }}>Regstair</Typography><Typography color="text.secondary" variant="body2">Registry routing and cache</Typography></Box><ThemeModeControl /></Stack><Box><Typography color="primary.main" sx={{ fontSize: 12, fontWeight: 750, textTransform: 'uppercase' }}>{eyebrow}</Typography><Typography component="h1" variant="h1">{title}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{subtitle}</Typography></Box><Paper variant="outlined" sx={{ borderTop: 3, borderTopColor: 'primary.main', p: { xs: 2.5, sm: 4 } }}>{children}</Paper><Typography color="text.secondary" sx={{ textAlign: 'center' }} variant="caption">Secure local access</Typography></Stack></Box> }

export function LoginPage() { const [error, setError] = useState(''), [busy, setBusy] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); try { await request('/admin/api/login', { username: data.get('username'), password: data.get('password') }); window.location.assign('/') } catch (failure) { setError(failure instanceof ApiError && failure.status === 429 ? 'Too many attempts. Wait before trying again.' : 'The username or password is incorrect.'); setBusy(false) } }; return <PublicFrame eyebrow="Secure access" title="Sign in" subtitle="Use your local Regstair account to manage registry access."><Box component="form" onSubmit={submit}><Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}<TextField required autoFocus autoComplete="username" name="username" label="Username" /><TextField required autoComplete="current-password" name="password" type="password" label="Password" /><Button disabled={busy} type="submit" variant="contained" size="large">{busy ? <CircularProgress size={22} /> : 'Sign in'}</Button></Stack></Box></PublicFrame> }

export function SetupPage() { const [error, setError] = useState(''), [busy, setBusy] = useState(false); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(''); const data = new FormData(event.currentTarget); const password = String(data.get('password')), confirmation = String(data.get('confirmation')); if (password !== confirmation) { setError('Passwords do not match.'); setBusy(false); return } try { const setup = await request<{ setup_token: string }>('/admin/api/setup'); await request('/admin/api/setup', { username: data.get('username'), display_name: data.get('display_name'), email: data.get('email'), password }, { 'X-Regstair-Setup-Token': setup.setup_token }); window.location.assign('/') } catch { setError('Setup could not be completed. Review the fields and try again.'); setBusy(false) } }; return <PublicFrame eyebrow="First-run ownership" wide title="Create the first administrator" subtitle="This one-time setup establishes ownership of this Regstair service."><Box component="form" onSubmit={submit}><Stack spacing={2}>{error && <Alert severity="error">{error}</Alert>}<TextField required autoFocus autoComplete="username" name="username" label="Username" /><TextField name="display_name" label="Display name" /><TextField name="email" type="email" label="Email" /><TextField required autoComplete="new-password" name="password" type="password" label="Password" helperText="15 to 128 characters" slotProps={{ htmlInput: { minLength: 15, maxLength: 128 } }} /><TextField required autoComplete="new-password" name="confirmation" type="password" label="Confirm password" /><Button disabled={busy} type="submit" variant="contained" size="large">{busy ? <CircularProgress size={22} /> : 'Create administrator'}</Button></Stack></Box></PublicFrame> }
