import ContentCopyRounded from '@mui/icons-material/ContentCopyRounded'
import DeleteOutlineRounded from '@mui/icons-material/DeleteOutlineRounded'
import KeyRounded from '@mui/icons-material/KeyRounded'
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FormEvent, useMemo, useState } from 'react'
import { apiRequest, ApiError } from '../api/client'
import { EmptyState, OperationalPanel, PageHeader, StatusSummary } from '../design/OperationalUI'

type Account = { username: string; display_name?: string; email?: string; access: string }
type Token = { id: string; label: string; ctime: string; expires_at: string; last_used_at?: string; revoked_at?: string }
type Credential = { source_id: string; username: string; ctime: string; mtime: string }
type Registry = { id: string; name: string; endpoint: string; pull: boolean; push: boolean; guidance?: string; routes: string[] }

const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Never'

export function AccountView({ account, tokens, credentials, registries, credentialsAvailable, onPassword, onCreateToken, onRevokeToken, onSaveCredential, onRemoveCredential, error }: { account: Account; tokens: Token[]; credentials: Credential[]; registries: Registry[]; credentialsAvailable: boolean; onPassword: (current: string, next: string) => void; onCreateToken: (label: string, days: number) => void; onRevokeToken: (id: string) => void; onSaveCredential: (source: string, username: string, secret: string) => void; onRemoveCredential: (source: string) => void; error?: string }) {
  const [passwordOpen, setPasswordOpen] = useState(false)
  const [tokenOpen, setTokenOpen] = useState(false)
  const [credentialSource, setCredentialSource] = useState('')
  const [destructive, setDestructive] = useState<{ kind: 'token' | 'credential'; id: string; label: string } | null>(null)
  const credentialBySource = useMemo(() => new Map(credentials.map((item) => [item.source_id, item])), [credentials])
  const submit = (handler: (data: FormData) => void) => (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); handler(new FormData(event.currentTarget)) }
  return <Stack spacing={4}>
    <PageHeader title="Account" subtitle="Your Regstair identity, Docker access, and registry credentials" />
    {error && <Alert severity="error">{error}</Alert>}
    <OperationalPanel title="Profile"><Stack direction={{ xs: 'column', sm: 'row' }} spacing={3} sx={{ alignItems: { sm: 'center' }, p: 2.25 }}><Box sx={{ flex: 1 }}><Typography sx={{ fontWeight: 700 }}>{account.display_name || account.username}</Typography><Typography color="text.secondary">{account.username}{account.email ? ` · ${account.email}` : ''}</Typography></Box><Chip label={account.access === 'admin' ? 'Administrator' : 'User'} /><Button startIcon={<KeyRounded />} onClick={() => setPasswordOpen(true)}>Change password</Button></Stack></OperationalPanel>
    <OperationalPanel title="Docker access" action={<Button variant="contained" onClick={() => setTokenOpen(true)}>Create token</Button>}><Typography color="text.secondary" sx={{ px: 2.25, pt: 2 }}>Use a token as your password with <code>docker login</code>.</Typography>{tokens.length === 0 ? <EmptyState title="No Docker tokens" detail="Create a time-limited token before signing in from a Docker client." /> : <Stack divider={<Divider />} sx={{ px: 2.25 }}>{tokens.map((token) => <Stack key={token.id} direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ alignItems: { md: 'center' }, py: 2 }}><Box sx={{ flex: 1 }}><Typography sx={{ fontWeight: 700 }}>{token.label}</Typography><Typography color="text.secondary" variant="body2">Expires {date(token.expires_at)} · Last used {date(token.last_used_at)}</Typography></Box><Button color="error" startIcon={<DeleteOutlineRounded />} onClick={() => setDestructive({ kind: 'token', id: token.id, label: token.label })}>Revoke</Button></Stack>)}</Stack>}</OperationalPanel>
    {!credentialsAvailable && <StatusSummary tone="warning" title="Credential storage unavailable" detail="An administrator must configure the credential encryption key before upstream credentials can be saved." />}
    <OperationalPanel title="Registry credentials"><Typography color="text.secondary" sx={{ px: 2.25, pt: 2 }}>Connect your own accounts to registries configured in Regstair. Secrets are verified before encrypted storage.</Typography>{registries.length === 0 ? <EmptyState title="No configured registries" detail="Add a registry before connecting credentials." /> : <Stack divider={<Divider />} sx={{ px: 2.25 }}>{registries.map((registry) => { const credential = credentialBySource.get(registry.id); return <Stack key={registry.id} direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ alignItems: { md: 'center' }, py: 2 }}><Box sx={{ flex: 1 }}><Typography sx={{ fontWeight: 700 }}>{registry.name}</Typography><Typography color="text.secondary" variant="body2">{registry.endpoint} · {registry.pull && registry.push ? 'Pull and push' : registry.push ? 'Push' : registry.pull ? 'Pull' : 'No active routes'}</Typography>{credential && <Typography variant="body2">Connected as {credential.username} · Verified {date(credential.mtime)}</Typography>}</Box><Button disabled={!credentialsAvailable} onClick={() => setCredentialSource(registry.id)}>{credential ? 'Replace' : 'Add credential'}</Button>{credential && <Button color="error" onClick={() => setDestructive({ kind: 'credential', id: registry.id, label: registry.name })}>Remove</Button>}</Stack> })}</Stack>}</OperationalPanel>
    <Dialog open={passwordOpen} onClose={() => setPasswordOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit((data) => onPassword(String(data.get('current')), String(data.get('next'))))}><DialogTitle>Change password</DialogTitle><DialogContent><Alert severity="warning" sx={{ mb: 2 }}>Changing your password signs out every active web session immediately.</Alert><Stack spacing={2}><TextField required name="current" type="password" label="Current password" /><TextField required name="next" type="password" label="New password" slotProps={{ htmlInput: { minLength: 15, maxLength: 128 } }} /></Stack></DialogContent><DialogActions><Button onClick={() => setPasswordOpen(false)}>Cancel</Button><Button type="submit" variant="contained">Change password</Button></DialogActions></Box></Dialog>
    <Dialog open={tokenOpen} onClose={() => setTokenOpen(false)} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit((data) => onCreateToken(String(data.get('label')), Number(data.get('days'))))}><DialogTitle>Create Docker token</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField required name="label" label="Label" /><FormControl><InputLabel>Expires</InputLabel><Select name="days" label="Expires" defaultValue="30"><MenuItem value="7">7 days</MenuItem><MenuItem value="30">30 days</MenuItem><MenuItem value="90">90 days</MenuItem></Select></FormControl></Stack></DialogContent><DialogActions><Button onClick={() => setTokenOpen(false)}>Cancel</Button><Button type="submit" variant="contained">Create token</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(credentialSource)} onClose={() => setCredentialSource('')} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit((data) => onSaveCredential(credentialSource, String(data.get('username')), String(data.get('secret'))))}><DialogTitle>Verify registry credential</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField required name="username" label="Upstream username" autoComplete="username" /><TextField required name="secret" type="password" label="Password, token, or robot secret" autoComplete="new-password" /></Stack></DialogContent><DialogActions><Button onClick={() => setCredentialSource('')}>Cancel</Button><Button type="submit" variant="contained">Verify and save</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(destructive)} onClose={() => setDestructive(null)} fullWidth maxWidth="xs"><DialogTitle>{destructive?.kind === 'token' ? 'Revoke Docker token?' : 'Remove registry credential?'}</DialogTitle><DialogContent><Alert severity="warning">{destructive?.kind === 'token' ? 'Clients using this token will lose access immediately.' : `Regstair will no longer use your credential for ${destructive?.label}.`}</Alert></DialogContent><DialogActions><Button onClick={() => setDestructive(null)}>Cancel</Button><Button color="error" variant="contained" onClick={() => { if (!destructive) return; destructive.kind === 'token' ? onRevokeToken(destructive.id) : onRemoveCredential(destructive.id); setDestructive(null) }}>{destructive?.kind === 'token' ? 'Revoke token' : 'Remove credential'}</Button></DialogActions></Dialog>
  </Stack>
}

export function AccountPage() {
  const client = useQueryClient(), [error, setError] = useState(''), [secret, setSecret] = useState('')
  const account = useQuery({ queryKey: ['account'], queryFn: () => apiRequest<Account>('/admin/api/account') })
  const tokens = useQuery({ queryKey: ['docker-tokens'], queryFn: () => apiRequest<{ tokens: Token[] }>('/admin/api/account/docker-tokens') })
  const registries = useQuery({ queryKey: ['registries'], queryFn: () => apiRequest<{ registries: Registry[] }>('/admin/api/registries') })
  const credentials = useQuery({ queryKey: ['credentials'], queryFn: () => apiRequest<{ credentials: Credential[] }>('/admin/api/account/registry-credentials'), retry: false })
  const mutate = useMutation({ mutationFn: ({ path, method, body }: { path: string; method: string; body?: unknown }) => apiRequest<{ secret?: string }>(path, { method, headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }), onSuccess: (result) => { setError(''); if (result?.secret) setSecret(result.secret); client.invalidateQueries() }, onError: (failure) => setError(failure instanceof ApiError ? failure.classification : 'The account change could not be completed.') })
  if (account.isLoading || tokens.isLoading || registries.isLoading || credentials.isLoading) return <Stack role="status" sx={{ alignItems: 'center', py: 10 }}><CircularProgress /></Stack>
  if (!account.data || !tokens.data || !registries.data) return <Alert severity="error">Account data could not be loaded.</Alert>
  return <><AccountView account={account.data} tokens={tokens.data.tokens} registries={registries.data.registries} credentials={credentials.data?.credentials ?? []} credentialsAvailable={!credentials.isError} error={error} onPassword={(current, next) => mutate.mutate({ path: '/admin/api/account/password', method: 'POST', body: { current_password: current, new_password: next } }, { onSuccess: () => window.location.assign('/login') })} onCreateToken={(label, days) => mutate.mutate({ path: '/admin/api/account/docker-tokens', method: 'POST', body: { label, expires_in_days: days } })} onRevokeToken={(id) => mutate.mutate({ path: `/admin/api/account/docker-tokens/${id}`, method: 'DELETE' })} onSaveCredential={(source, username, value) => mutate.mutate({ path: `/admin/api/account/registry-credentials/${source}/verify-and-save`, method: 'POST', body: { username, secret: value } })} onRemoveCredential={(source) => mutate.mutate({ path: `/admin/api/account/registry-credentials/${source}`, method: 'DELETE', body: { confirm: true } })} />
    <Dialog open={Boolean(secret)} fullWidth maxWidth="sm"><DialogTitle>Docker token created</DialogTitle><DialogContent><Alert severity="warning">This secret is shown once. Store it before closing.</Alert><Box sx={{ bgcolor: 'action.hover', fontFamily: 'monospace', my: 2, overflowWrap: 'anywhere', p: 2 }}>{secret}</Box><Button startIcon={<ContentCopyRounded />} onClick={() => navigator.clipboard.writeText(secret)}>Copy token</Button></DialogContent><DialogActions><Button variant="contained" onClick={() => setSecret('')}>I have stored this token</Button></DialogActions></Dialog></>
}
