import { Alert, Box, Chip, CircularProgress, FormControl, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { apiRequest } from '../api/client'
import { EmptyState, OperationalPanel, PageHeader } from '../design/OperationalUI'

type Event = { id: number; timestamp: string; action: string; action_label: string; outcome: string; actor: string; target: string; detail?: string; correlation_id?: string }
type Response = { events: Event[]; actions: { action: string; label: string }[] }

export function AuditView({ data }: { data: Response }) {
  const [action, setAction] = useState(''), [outcome, setOutcome] = useState(''), [search, setSearch] = useState('')
  const events = useMemo(() => data.events.filter((event) => (!action || event.action === action) && (!outcome || event.outcome === outcome) && (!search || `${event.actor} ${event.target} ${event.correlation_id ?? ''}`.toLowerCase().includes(search.toLowerCase()))), [data.events, action, outcome, search])
  return <Stack spacing={3}><PageHeader eyebrow="Security" title="Audit" subtitle="Security-sensitive identity, access, token, and credential activity" /><OperationalPanel title="Filter activity"><Stack direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ p: 2.25 }}><FormControl size="small" sx={{ minWidth: 240 }}><InputLabel>Action</InputLabel><Select label="Action" value={action} onChange={(event) => setAction(event.target.value)}><MenuItem value="">All actions</MenuItem>{data.actions.map((item) => <MenuItem key={item.action} value={item.action}>{item.label}</MenuItem>)}</Select></FormControl><FormControl size="small" sx={{ minWidth: 160 }}><InputLabel>Outcome</InputLabel><Select label="Outcome" value={outcome} onChange={(event) => setOutcome(event.target.value)}><MenuItem value="">All outcomes</MenuItem><MenuItem value="success">Success</MenuItem><MenuItem value="failure">Failure</MenuItem></Select></FormControl><TextField size="small" fullWidth label="Actor, target, or correlation" value={search} onChange={(event) => setSearch(event.target.value)} /></Stack></OperationalPanel><OperationalPanel title={`Audit events · ${events.length}`}>{events.length === 0 ? <EmptyState title="No matching audit events" detail="Change the filters to broaden the security activity shown here." /> : <Stack spacing={0} divider={<Box sx={{ borderTop: 1, borderColor: 'divider' }} />} sx={{ px: 2.25 }}>{events.map((event) => <Box key={event.id} sx={{ display: 'grid', gap: 1, gridTemplateColumns: { xs: '1fr auto', md: '180px minmax(220px, 1fr) 180px 180px auto' }, py: 2 }}><Typography color="text.secondary" variant="body2">{new Date(event.timestamp).toLocaleString()}</Typography><Typography sx={{ fontWeight: 700 }}>{event.action_label}</Typography><Typography variant="body2">{event.actor}</Typography><Typography variant="body2">{event.target}</Typography><Chip color={event.outcome === 'success' ? 'success' : 'error'} label={event.outcome} size="small" variant="outlined" /><Typography color="text.secondary" variant="body2" sx={{ gridColumn: { xs: '1 / -1', md: '2 / -1' } }}>{event.detail || event.correlation_id}</Typography></Box>)}</Stack>}</OperationalPanel></Stack>
}

export function AuditPage() { const query = useQuery({ queryKey: ['audit'], queryFn: () => apiRequest<Response>('/admin/api/audit') }); if (query.isLoading) return <Stack role="status" sx={{ alignItems: 'center', py: 10 }}><CircularProgress /></Stack>; if (!query.data) return <Alert severity="error">Audit activity could not be loaded.</Alert>; return <AuditView data={query.data} /> }
